[tool.poetry]
name = "audiotranscriber"
version = "0.1.0"
description = ""
authors = ["alby11 <alby11@duck.com>"]
readme = "README.md"

[tool.poetry.dependencies]
python = "^3.12"


[build-system]
requires = ["poetry-core"]
build-backend = "poetry.core.masonry.api"
